FLAGS=-lpthread
all: ex1 ex2 ex3 ex5 ex6


ex1: ex1.c
	gcc -o ex1 ex1.c ${FLAGS}

ex2: ex2.c
	gcc -o ex2 ex2.c ${FLAGS}

ex3: ex3.c
	gcc -o ex3 ex3.c ${FLAGS}

ex5: ex5.c
	gcc -o ex5 ex5.c ${FLAGS}

ex6: ex6.c
	gcc -o ex6 ex6.c ${FLAGS}

atomic: atomic.c
	gcc -o atomic atomic.c ${FLAGS}