CFLAGS=-Wall -Wextra -pedantic -std=gnu17 -O0

all: ex1a ex1b ex2 ex3 ex4

ex1a: ex1_a.c 
	gcc ex1_a.c -o ex1a -lpthread ${CFLAGS}

ex1b: ex1_b.c 
	gcc ex1_b.c -o ex1b -lpthread ${CFLAGS}

ex2: ex2.c 
	gcc ex2.c -o ex2 ${CFLAGS}

ex3: 
	echo "TODO: compléter le makefile pour l'exercice 3"

ex4: 
	echo "TODO: compléter le makefile pour l'exercice 4"