CFLAGS=-Wall -Wextra -pedantic -std=gnu17 -O0

all: ex1 ex2 ex3 ex4

ex1: ex1.c 
	gcc ex1.c -o ex1 -lpthread ${CFLAGS}

ex2: ex2.c 
	gcc ex2.c -o ex2 ${CFLAGS}

ex3: 
	echo "TODO: compléter le makefile pour l'exercice 3"

ex4: 
	echo "TODO: compléter le makefile pour l'exercice 4"