
SRC_DIR = ./src/

all: ex1 ex2 ex3 ex5 ex6

ex1: $(SRC_DIR)ex1.c
	gcc -o ex1 $(SRC_DIR)ex1.c -lpthread

ex2: $(SRC_DIR)ex2.c
	gcc -o ex2 $(SRC_DIR)ex2.c -lpthread

ex3: $(SRC_DIR)ex3.c
	gcc -o ex3 $(SRC_DIR)ex3.c -lpthread

ex5: $(SRC_DIR)ex5.c
	gcc -o ex5 $(SRC_DIR)ex5.c -lpthread

ex6: $(SRC_DIR)ex5.c
	gcc -o ex6 $(SRC_DIR)ex6.c -lpthread
